### ISSUE TITLE
Custom CKEditor not showing up with fluid content elements

### ISSUE THREAD

**Issue by MrMooky** [FluidTYPO3/fluidcontent#422]
TYPO3 8.7.4 with Fluidcontent 5.2.0 (from TER) does not seem to use the preset I defined:

`RTE.default.preset = siteway_presets`

It works fine with a regular text element, or any other TYPO3 default, though.

**Regular Text Element**

![screen shot 2017-09-06 at 9 48 23 am](https://user-images.githubusercontent.com/3603346/30100273-8f5ac7c6-92e8-11e7-8909-27897e8fe8bf.png)

**Custom Fluidcontent element**

![screen shot 2017-09-06 at 9 48 52 am](https://user-images.githubusercontent.com/3603346/30100297-a5539f1c-92e8-11e7-8762-15fc3725b0f6.png)

**Comment by rupasix** [comment]
Your issue is connected with this: https://github.com/FluidTYPO3/flux/issues/1388, and was repaired here: https://github.com/FluidTYPO3/flux/pull/1426.

Please remember that "fluidcontent" is now considered obsolete so push next issues to flux repo.

**Comment by MrMooky** [comment]
> Please remember that "fluidcontent" is now considered obsolete...

Is there a short tutorial on how to create custom content elements with flux? We've been using fluidcontent for some time now and never heard of the possibility to build custom elements with flux.

~~Also, the fix you linked to did not change a thing. The default RTE config still shows up, I even hardcoded the full preset into the flux Text.php file.~~ **UPDATE**: forgot to update the ViewHelper file, finally works fine for now. :)

**Comment by rupasix** [comment]
You can read more about that here ("OBSOLETE!" section) https://github.com/FluidTYPO3/fluidcontent/blob/development/README.md

I haven't tested it yet because new flux, capable to handling new CType, is still on "development" branch :)

**Comment by NamelessCoder** [comment]
> Is there a short tutorial on how to create custom content elements with flux?

There is. In its full form, that guide is:

```
Uninstall fluidcontent
```

Flux takes over automatically. The templates are 100% identical.

Closing this issue since it's fixed in https://github.com/FluidTYPO3/flux/pull/1426 and would belong in Flux's issue tracker anyway.

**Comment by MrMooky** [comment]
@NamelessCoder Sorry about posting in such an old issue, but just uninstalling fluidcontent caused all elements to display: `Content Element with uid "X" and type "fluidcontent_content" has no rendering definition!`. Any idea why that happens?

**Comment by MrMooky** [comment]
> Your issue is connected with this: FluidTYPO3/flux#1388, and was repaired here: FluidTYPO3/flux#1426.

That does not fix it. No effect at all. Even after almost half a year. :/
